<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4046a8ef-0b52-4a38-924e-2b8e9b688c35</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\resources\GuideTouritis.png\**" />
    <Content Remove="wwwroot\resources\GuideTouritis.png\**" />
    <EmbeddedResource Remove="wwwroot\resources\GuideTouritis.png\**" />
    <None Remove="wwwroot\resources\GuideTouritis.png\**" />
  </ItemGroup>

  <ItemGroup>

   <Folder Include="Controllers\Messages\" />
    <Folder Include="Controllers\Customers\" />
    <Folder Include="wwwroot\css\" />
    <Folder Include="wwwroot\Img\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\RealEstateApp.Core.Application\RealEstateApp.Core.Application.csproj" />
    <ProjectReference Include="..\..\Infraestructure\RealEstateApp.Infraestructure.Identity\RealEstateApp.Infraestructure.Identity.csproj" />
    <ProjectReference Include="..\..\RealStateApp.IOC\RealStateApp.IOC.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.17">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\RealEstateApp.Core.Application\RealEstateApp.Core.Application.csproj" />
  </ItemGroup>

</Project>
