name: Validar y Compilar PR hacia Development

on:
  pull_request:
    branches: [ "development" ]

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Validar nombre de la rama Feature
      run: |
        BRANCH_NAME="${{ github.head_ref }}"
        if [[ ! "$BRANCH_NAME" =~ ^[Ff]eature/ ]]; then
          echo "🛑 ERROR CRÍTICO: La rama de origen debe empezar con 'feature/' o 'Feature/'. Origen actual: $BRANCH_NAME"
          exit 1
        fi

    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Compilar el proyecto
      run: dotnet build --no-restore